#include "codegen.h"
#include "assembler.h"
#include "heap.h"
#include "string.h"
#include <stdarg.h>

static void putc_c(codegen_t*c,char v){if(c->size+1>=c->capacity){u32 n=c->capacity?c->capacity*2:2048;char*p=(char*)kmalloc(n);if(!p)return;if(c->buf){memcpy(p,c->buf,c->size);kfree(c->buf);}c->buf=p;c->capacity=n;}c->buf[c->size++]=v;c->buf[c->size]=0;}
static void puts_c(codegen_t*c,const char*s){while(*s)putc_c(c,*s++);}
static void putnum(codegen_t*c,i32 v){char b[16];u32 n=0;u32 x=(u32)(v<0?-v:v);if(v<0)putc_c(c,'-');if(!x){putc_c(c,'0');return;}while(x){b[n++]=(char)('0'+x%10);x/=10;}while(n)putc_c(c,b[--n]);}
void codegen_init(codegen_t*c){memset(c,0,sizeof(*c));}
void codegen_emit(codegen_t*c,const char*f,...){__builtin_va_list a;const char*p;__builtin_va_start(a,f);for(p=f;*p;p++){if(*p!='%'){putc_c(c,*p);continue;}p++;if(*p=='s')puts_c(c,__builtin_va_arg(a,const char*));else if(*p=='u')putnum(c,(i32)__builtin_va_arg(a,u32));else if(*p=='d')putnum(c,__builtin_va_arg(a,i32));}__builtin_va_end(a);putc_c(c,'\n');}
static symbol_t*find_var(ast_node_t*n,const char*s){u32 i;if(!n)return 0;if(n->kind==AST_VAR_DECL&&!strcmp(n->as.var.name,s))return n->as.var.sym;if(n->kind==AST_COMPOUND||n->kind==AST_PROGRAM)for(i=0;i<n->as.list.count;i++){symbol_t*x=find_var(n->as.list.items[i],s);if(x)return x;}if(n->kind==AST_FUNC_DECL){for(i=0;i<n->as.func.params.count;i++)if(!strcmp(n->as.func.params.items[i]->as.var.name,s))return n->as.func.params.items[i]->as.var.sym;return find_var(n->as.func.body,s);}return 0;}
static void collect_strings(codegen_t*c,ast_node_t*n){u32 i;if(!n)return;if(n->kind==AST_STRING){n->as.string.str_label=c->strings++;return;}if(n->kind==AST_PROGRAM||n->kind==AST_COMPOUND)for(i=0;i<n->as.list.count;i++)collect_strings(c,n->as.list.items[i]);if(n->kind==AST_FUNC_DECL)collect_strings(c,n->as.func.body);if(n->kind==AST_VAR_DECL)collect_strings(c,n->as.var.init);if(n->kind==AST_BINARY||n->kind==AST_ASSIGN){collect_strings(c,n->as.binary.left);collect_strings(c,n->as.binary.right);}if(n->kind==AST_UNARY)collect_strings(c,n->as.unary.operand);if(n->kind==AST_CALL){collect_strings(c,n->as.call.callee);for(i=0;i<n->as.call.args.count;i++)collect_strings(c,n->as.call.args.items[i]);}}
static void emit_strings(codegen_t*c,ast_node_t*n){u32 i,j;if(!n)return;if(n->kind==AST_STRING){codegen_emit(c,"str_%u:",n->as.string.str_label);for(j=0;j<n->as.string.str_len;j++){u8 v=(u8)n->as.string.str[j];if(v=='\\'&&j+1<n->as.string.str_len){char e=n->as.string.str[++j];v=e=='n'?'\n':e=='t'?'\t':e;}codegen_emit(c,"db %u",(u32)v);}codegen_emit(c,"db 0");return;}if(n->kind==AST_PROGRAM||n->kind==AST_COMPOUND)for(i=0;i<n->as.list.count;i++)emit_strings(c,n->as.list.items[i]);if(n->kind==AST_FUNC_DECL)emit_strings(c,n->as.func.body);if(n->kind==AST_VAR_DECL)emit_strings(c,n->as.var.init);if(n->kind==AST_BINARY||n->kind==AST_ASSIGN){emit_strings(c,n->as.binary.left);emit_strings(c,n->as.binary.right);}if(n->kind==AST_UNARY)emit_strings(c,n->as.unary.operand);if(n->kind==AST_CALL){emit_strings(c,n->as.call.callee);for(i=0;i<n->as.call.args.count;i++)emit_strings(c,n->as.call.args.items[i]);}}
static void offsets(ast_node_t*n,i32*off){u32 i;if(!n)return;if(n->kind==AST_VAR_DECL&&!n->as.var.is_global){u32 size=n->as.var.var_type->type?n->as.var.var_type->type->size:4;if(!size)size=4;size=(size+3)&~3;*off-=(i32)size;if(n->as.var.sym)n->as.var.sym->stack_offset=*off;return;}if(n->kind==AST_COMPOUND||n->kind==AST_PROGRAM)for(i=0;i<n->as.list.count;i++)offsets(n->as.list.items[i],off);}
static void addr(codegen_t*c,ast_node_t*n,ast_node_t*scope);
static void expr(codegen_t*c,ast_node_t*n,ast_node_t*scope){u32 i;if(!n)return;switch(n->kind){case AST_NUMBER:codegen_emit(c,"mov eax, %d",n->as.int_value);break;case AST_IDENT:{symbol_t*s=find_var(scope,n->as.ident.name);if(s)codegen_emit(c,"mov eax, [ebp%d]",s->stack_offset);else codegen_emit(c,"mov eax, 0");break;}case AST_STRING:codegen_emit(c,"mov eax, str_%u",n->as.string.str_label);break;case AST_UNARY:if(n->as.unary.op==TOK_STAR){expr(c,n->as.unary.operand,scope);codegen_emit(c,"mov eax, [eax]");}else if(n->as.unary.op==TOK_BIT_AND)addr(c,n->as.unary.operand,scope);else{expr(c,n->as.unary.operand,scope);if(n->as.unary.op==TOK_MINUS)codegen_emit(c,"neg eax");if(n->as.unary.op==TOK_BIT_NOT)codegen_emit(c,"not eax");if(n->as.unary.op==TOK_INC)codegen_emit(c,"inc eax");if(n->as.unary.op==TOK_DEC)codegen_emit(c,"dec eax");}break;case AST_INDEX:addr(c,n,scope);codegen_emit(c,"mov eax, [eax]");break;case AST_MEMBER:addr(c,n,scope);codegen_emit(c,"mov eax, [eax]");break;case AST_ASSIGN:addr(c,n->as.binary.left,scope);codegen_emit(c,"push eax");expr(c,n->as.binary.right,scope);codegen_emit(c,"pop ebx");codegen_emit(c,"mov [ebx], eax");break;case AST_BINARY:expr(c,n->as.binary.left,scope);codegen_emit(c,"push eax");expr(c,n->as.binary.right,scope);codegen_emit(c,"mov ebx, eax");codegen_emit(c,"pop eax");switch(n->as.binary.op){case TOK_PLUS:codegen_emit(c,"add eax, ebx");break;case TOK_MINUS:codegen_emit(c,"sub eax, ebx");break;case TOK_STAR:codegen_emit(c,"imul ebx");break;case TOK_SLASH:codegen_emit(c,"cdq");codegen_emit(c,"idiv ebx");break;case TOK_PERCENT:codegen_emit(c,"cdq");codegen_emit(c,"idiv ebx");codegen_emit(c,"mov eax, edx");break;default:codegen_emit(c,"cmp eax, ebx");codegen_emit(c,"setne al");codegen_emit(c,"movzx eax, al");break;}break;case AST_CALL:if(n->as.call.callee->kind==AST_IDENT&&!strcmp(n->as.call.callee->as.ident.name,"galio_exit")){expr(c,n->as.call.args.items[0],scope);codegen_emit(c,"mov ebx, eax");codegen_emit(c,"mov eax, 1");codegen_emit(c,"int 128");break;}if(n->as.call.callee->kind==AST_IDENT&&!strcmp(n->as.call.callee->as.ident.name,"malloc")){expr(c,n->as.call.args.items[0],scope);codegen_emit(c,"mov ebx, eax");codegen_emit(c,"mov eax, 45");codegen_emit(c,"int 128");break;}for(i=n->as.call.args.count;i;i--){expr(c,n->as.call.args.items[i-1],scope);codegen_emit(c,"push eax");}if(n->as.call.callee->kind==AST_IDENT)codegen_emit(c,"call %s",n->as.call.callee->as.ident.name);if(n->as.call.args.count)codegen_emit(c,"add esp, %u",n->as.call.args.count*4);break;default:break;}}
static void addr(codegen_t*c,ast_node_t*n,ast_node_t*scope){if(n->kind==AST_IDENT){symbol_t*s=find_var(scope,n->as.ident.name);if(s)codegen_emit(c,"lea eax, [ebp%d]",s->stack_offset);else codegen_emit(c,"mov eax, 0");}else if(n->kind==AST_UNARY&&n->as.unary.op==TOK_STAR)expr(c,n->as.unary.operand,scope);else if(n->kind==AST_INDEX){expr(c,n->as.index.base,scope);codegen_emit(c,"push eax");expr(c,n->as.index.index,scope);codegen_emit(c,"imul eax, 4");codegen_emit(c,"pop ebx");codegen_emit(c,"add eax, ebx");}else if(n->kind==AST_MEMBER){addr(c,n->as.member.base,scope);}else expr(c,n,scope);}
static void stmt(codegen_t*c,ast_node_t*n,ast_node_t*scope,u32*brk,u32*cont){u32 i,a,b,oldb,oldc;if(!n)return;switch(n->kind){case AST_COMPOUND:for(i=0;i<n->as.list.count;i++)stmt(c,n->as.list.items[i],scope,brk,cont);break;case AST_VAR_DECL:if(n->as.var.init){expr(c,n->as.var.init,scope);codegen_emit(c,"mov [ebp%d], eax",n->as.var.sym->stack_offset);}break;case AST_EXPR_STMT:expr(c,n->as.expr_stmt.expr,scope);break;case AST_RETURN:if(n->as.ret.expr)expr(c,n->as.ret.expr,scope);codegen_emit(c,"jmp func_end_%u",c->current_end);break;case AST_IF:a=c->labels++;b=c->labels++;expr(c,n->as.branch.cond,scope);codegen_emit(c,"test eax, eax");codegen_emit(c,"je label_%u",a);stmt(c,n->as.branch.then_body,scope,brk,cont);codegen_emit(c,"jmp label_%u",b);codegen_emit(c,"label_%u:",a);stmt(c,n->as.branch.else_body,scope,brk,cont);codegen_emit(c,"label_%u:",b);break;case AST_WHILE:a=c->labels++;b=c->labels++;oldb=*brk;oldc=*cont;*brk=b;*cont=a;codegen_emit(c,"label_%u:",a);expr(c,n->as.branch.cond,scope);codegen_emit(c,"test eax, eax");codegen_emit(c,"je label_%u",b);stmt(c,n->as.branch.then_body,scope,brk,cont);codegen_emit(c,"jmp label_%u",a);codegen_emit(c,"label_%u:",b);*brk=oldb;*cont=oldc;break;case AST_FOR:a=c->labels++;b=c->labels++;if(n->as.for_loop.init)expr(c,n->as.for_loop.init,scope);codegen_emit(c,"label_%u:",a);if(n->as.for_loop.cond){expr(c,n->as.for_loop.cond,scope);codegen_emit(c,"test eax, eax");codegen_emit(c,"je label_%u",b);}oldb=*brk;oldc=*cont;*brk=b;*cont=a;stmt(c,n->as.for_loop.body,scope,brk,cont);if(n->as.for_loop.step)expr(c,n->as.for_loop.step,scope);codegen_emit(c,"jmp label_%u",a);codegen_emit(c,"label_%u:",b);*brk=oldb;*cont=oldc;break;case AST_DO_WHILE:a=c->labels++;b=c->labels++;oldb=*brk;oldc=*cont;*brk=b;*cont=a;codegen_emit(c,"label_%u:",a);stmt(c,n->as.do_loop.body,scope,brk,cont);expr(c,n->as.do_loop.cond,scope);codegen_emit(c,"test eax, eax");codegen_emit(c,"jne label_%u",a);codegen_emit(c,"label_%u:",b);*brk=oldb;*cont=oldc;break;case AST_BREAK:codegen_emit(c,"jmp label_%u",*brk);break;case AST_CONTINUE:codegen_emit(c,"jmp label_%u",*cont);break;default:break;}}
int gc_codegen_ast(ast_node_t*ast,codegen_t*c){u32 i;collect_strings(c,ast);for(i=0;i<ast->as.list.count;i++){ast_node_t*f=ast->as.list.items[i];if(f->kind!=AST_FUNC_DECL)continue;i32 off=0;c->current_end=c->labels++;offsets(f->as.func.body,&off);codegen_emit(c,"%s:",f->as.func.name);codegen_emit(c,"push ebp");codegen_emit(c,"mov ebp, esp");if(off)codegen_emit(c,"sub esp, %u",(u32)-off);{u32 none=0xffffffff;stmt(c,f->as.func.body,f->as.func.body,&none,&none);}codegen_emit(c,"func_end_%u:",c->current_end);codegen_emit(c,"mov esp, ebp");codegen_emit(c,"pop ebp");codegen_emit(c,"ret");}emit_strings(c,ast);return 0;}
int gc_codegen_source(const char*s,u8**code,u32*code_size,u8**data,u32*data_size,u32*entry){gc_lexer_t l;gc_parser_t p;symtab_t st;codegen_t c;ast_node_t*a;gc_lexer_init(&l,s);symtab_init(&st);if(gc_parser_init(&p,&l,&st))return -4;a=gc_parse_program(&p);if(!a||p.error_count){ast_free(a);return -5;}codegen_init(&c);gc_codegen_ast(a,&c);if(gc_assemble(c.buf,code,code_size,data,data_size,entry)){kfree(c.buf);ast_free(a);return -10;}kfree(c.buf);ast_free(a);return 0;}
