#include "parser.h"
#include "heap.h"
#include "string.h"

static u32 hash_name(const char *s,u32 n){u32 h=5381,i;for(i=0;i<n;i++)h=((h<<5)+h)+(u8)s[i];return h%GC_SCOPE_BUCKETS;}
static char *dup_n(const char*s,u32 n){char*p=(char*)kmalloc(n+1);if(p){memcpy(p,s,n);p[n]=0;}return p;}
static void list_add(ast_list_t*l,ast_node_t*n){if(!n)return;if(l->count==l->capacity){u32 c=l->capacity?l->capacity*2:8;ast_node_t**p=(ast_node_t**)kmalloc(c*sizeof(*p));if(!p)return;if(l->items){memcpy(p,l->items,l->count*sizeof(*p));kfree(l->items);}l->items=p;l->capacity=c;}l->items[l->count++]=n;}
ast_node_t*ast_new(ast_kind_t k){ast_node_t*n=(ast_node_t*)kmalloc(sizeof(*n));if(n){memset(n,0,sizeof(*n));n->kind=k;}return n;}
ast_node_t*ast_number(i32 v){ast_node_t*n=ast_new(AST_NUMBER);if(n){n->as.int_value=v;n->type=type_int;}return n;}
ast_node_t*ast_ident(const char*s,u32 n){ast_node_t*x=ast_new(AST_IDENT);if(x){x->as.ident.name=dup_n(s,n);x->as.ident.name_len=n;}return x;}
ast_node_t*ast_string_node(const char*s,u32 n){ast_node_t*x=ast_new(AST_STRING);if(x){x->as.string.str=dup_n(s,n);x->as.string.str_len=n;}return x;}
ast_node_t*ast_binary(ast_kind_t k,gc_token_kind_t op,ast_node_t*l,ast_node_t*r){ast_node_t*n=ast_new(k);if(n){n->as.binary.left=l;n->as.binary.right=r;n->as.binary.op=op;}return n;}
ast_node_t*ast_unary(ast_kind_t k,gc_token_kind_t op,ast_node_t*x){ast_node_t*n=ast_new(k);if(n){n->as.unary.operand=x;n->as.unary.op=op;}return n;}
void ast_free(ast_node_t*n){u32 i;if(!n)return;switch(n->kind){case AST_PROGRAM:case AST_COMPOUND:case AST_STRUCT_DECL:for(i=0;i<n->as.list.count;i++)ast_free(n->as.list.items[i]);kfree(n->as.list.items);break;case AST_FUNC_DECL:for(i=0;i<n->as.func.params.count;i++)ast_free(n->as.func.params.items[i]);kfree(n->as.func.params.items);ast_free(n->as.func.return_type);ast_free(n->as.func.body);kfree(n->as.func.name);break;case AST_VAR_DECL:kfree(n->as.var.name);ast_free(n->as.var.var_type);ast_free(n->as.var.init);break;case AST_EXPR_STMT:ast_free(n->as.expr_stmt.expr);break;case AST_RETURN:ast_free(n->as.ret.expr);break;case AST_IF:case AST_WHILE:ast_free(n->as.branch.cond);ast_free(n->as.branch.then_body);ast_free(n->as.branch.else_body);break;case AST_FOR:ast_free(n->as.for_loop.init);ast_free(n->as.for_loop.cond);ast_free(n->as.for_loop.step);ast_free(n->as.for_loop.body);break;case AST_DO_WHILE:ast_free(n->as.do_loop.body);ast_free(n->as.do_loop.cond);break;case AST_CALL:ast_free(n->as.call.callee);for(i=0;i<n->as.call.args.count;i++)ast_free(n->as.call.args.items[i]);kfree(n->as.call.args.items);break;case AST_BINARY:case AST_ASSIGN:ast_free(n->as.binary.left);ast_free(n->as.binary.right);break;case AST_UNARY:ast_free(n->as.unary.operand);break;case AST_INDEX:ast_free(n->as.index.base);ast_free(n->as.index.index);break;case AST_MEMBER:ast_free(n->as.member.base);kfree(n->as.member.name);break;case AST_IDENT:kfree(n->as.ident.name);break;case AST_STRING:kfree(n->as.string.str);break;case AST_TYPEDEF:kfree(n->as.typedef_decl.name);break;default:break;}kfree(n);}
void symtab_init(symtab_t*s){memset(s,0,sizeof(*s));s->scope_count=1;}
void symtab_push_scope(symtab_t*s){if(s->scope_count<MAX_SCOPE_DEPTH){memset(&s->scopes[s->scope_count],0,sizeof(scope_t));s->scope_count++;}}
void symtab_pop_scope(symtab_t*s){if(s->scope_count>1)s->scope_count--;}
static symbol_t*find(scope_t*s,const char*n,u32 z){symbol_t*x=s->buckets[hash_name(n,z)];while(x){if(x->name_len==z&&!strncmp(x->name,n,z))return x;x=x->next;}return 0;}
symbol_t*symtab_lookup_current(symtab_t*s,const char*n,u32 z){return find(&s->scopes[s->scope_count-1],n,z);}
symbol_t*symtab_lookup(symtab_t*s,const char*n,u32 z){u32 i=s->scope_count;symbol_t*x;while(i){x=find(&s->scopes[--i],n,z);if(x)return x;}return 0;}
symbol_t*symtab_insert(symtab_t*s,const char*n,u32 z,symbol_kind_t k){u32 l=s->scope_count-1,b=hash_name(n,z);symbol_t*x=(symbol_t*)kmalloc(sizeof(*x));if(!x)return 0;memset(x,0,sizeof(*x));x->name=dup_n(n,z);x->name_len=z;x->kind=k;x->scope_level=l;x->next=s->scopes[l].buckets[b];s->scopes[l].buckets[b]=x;return x;}
static void advance_p(gc_parser_t*p){p->current=p->peek;gc_lex_next(p->lexer,&p->peek);}
static u8 take(gc_parser_t*p,gc_token_kind_t k){if(p->current.kind!=k)return 0;advance_p(p);return 1;}
static u8 expect(gc_parser_t*p,gc_token_kind_t k){if(take(p,k))return 1;p->error_count++;return 0;}
static ast_node_t*type_node(gc_type_t*t){ast_node_t*n=ast_new(AST_NUMBER);if(n)n->type=t;return n;}
static gc_type_t*parse_type(gc_parser_t*p){gc_type_t*t=0;symbol_t*x;char name[128];u32 n=0;if(p->current.kind==TOK_INT){t=type_int;advance_p(p);}else if(p->current.kind==TOK_CHAR_KW){t=type_char;advance_p(p);}else if(p->current.kind==TOK_VOID){t=type_void;advance_p(p);}else if(p->current.kind==TOK_STRUCT||p->current.kind==TOK_UNION){u8 un=p->current.kind==TOK_UNION;advance_p(p);if(p->current.kind!=TOK_IDENT){p->error_count++;return type_int;}while(n+1<sizeof(name)&&n<p->current.length){name[n]=p->current.start[n];n++;}name[n]=0;advance_p(p);t=type_struct(name,un);if(take(p,TOK_LBRACE)){while(p->current.kind!=TOK_RBRACE&&p->current.kind!=TOK_EOF){gc_type_t*m=parse_type(p);if(p->current.kind!=TOK_IDENT){p->error_count++;break;}char mn[128];u32 ml=p->current.length;memcpy(mn,p->current.start,ml);mn[ml]=0;advance_p(p);type_add_member(t,mn,m);expect(p,TOK_SEMICOLON);}expect(p,TOK_RBRACE);}}else if(p->current.kind==TOK_IDENT){x=symtab_lookup(p->symtab,p->current.start,p->current.length);if(!x||x->kind!=SYM_TYPE){p->error_count++;return type_int;}t=x->type;advance_p(p);}else{p->error_count++;return type_int;}while(take(p,TOK_STAR))t=type_pointer(t);return t;}
static ast_node_t*expr(gc_parser_t*p);static ast_node_t*stmt(gc_parser_t*p);static ast_node_t*primary(gc_parser_t*p){ast_node_t*n=0;if(p->current.kind==TOK_NUMBER||p->current.kind==TOK_CHAR){n=ast_number(p->current.value);advance_p(p);}else if(p->current.kind==TOK_STRING){n=ast_string_node(p->current.start+1,p->current.length>1?p->current.length-2:0);advance_p(p);}else if(p->current.kind==TOK_IDENT){n=ast_ident(p->current.start,p->current.length);advance_p(p);}else if(take(p,TOK_LPAREN)){n=expr(p);expect(p,TOK_RPAREN);}else{p->error_count++;return 0;}for(;;){if(take(p,TOK_LPAREN)){ast_node_t*c=ast_new(AST_CALL);c->as.call.callee=n;while(p->current.kind!=TOK_RPAREN&&p->current.kind!=TOK_EOF){list_add(&c->as.call.args,expr(p));if(!take(p,TOK_COMMA))break;}expect(p,TOK_RPAREN);n=c;}else if(take(p,TOK_LBRACKET)){ast_node_t*x=ast_new(AST_INDEX);x->as.index.base=n;x->as.index.index=expr(p);expect(p,TOK_RBRACKET);n=x;}else if(p->current.kind==TOK_DOT||p->current.kind==TOK_ARROW){u8 ar=p->current.kind==TOK_ARROW;advance_p(p);if(p->current.kind!=TOK_IDENT){p->error_count++;return n;}ast_node_t*x=ast_new(AST_MEMBER);x->as.member.base=n;x->as.member.name=dup_n(p->current.start,p->current.length);x->as.member.name_len=p->current.length;x->as.member.arrow=ar;advance_p(p);n=x;}else if(p->current.kind==TOK_INC||p->current.kind==TOK_DEC){n=ast_unary(AST_UNARY,p->current.kind,n);n->as.unary.is_postfix=1;advance_p(p);}else break;}return n;}
static ast_node_t*unary(gc_parser_t*p){gc_token_kind_t k=p->current.kind;if(k==TOK_MINUS||k==TOK_PLUS||k==TOK_LOGICAL_NOT||k==TOK_BIT_NOT||k==TOK_STAR||k==TOK_BIT_AND||k==TOK_INC||k==TOK_DEC){advance_p(p);return ast_unary(AST_UNARY,k,unary(p));}return primary(p);}
static u32 prec(gc_token_kind_t k){if(k==TOK_ASSIGN||k==TOK_PLUS_ASSIGN||k==TOK_MINUS_ASSIGN||k==TOK_STAR_ASSIGN||k==TOK_SLASH_ASSIGN||k==TOK_PERCENT_ASSIGN)return 1;if(k==TOK_LOGICAL_OR)return 2;if(k==TOK_LOGICAL_AND)return 3;if(k==TOK_EQ||k==TOK_NE)return 4;if(k==TOK_LT||k==TOK_GT||k==TOK_LE||k==TOK_GE)return 5;if(k==TOK_PLUS||k==TOK_MINUS)return 6;if(k==TOK_STAR||k==TOK_SLASH||k==TOK_PERCENT)return 7;return 0;}
static ast_node_t*binary(gc_parser_t*p,u32 min){ast_node_t*l=unary(p);while(l&&prec(p->current.kind)>=min){gc_token_kind_t k=p->current.kind;u32 q=prec(k);advance_p(p);l=ast_binary(k==TOK_ASSIGN||k==TOK_PLUS_ASSIGN||k==TOK_MINUS_ASSIGN||k==TOK_STAR_ASSIGN||k==TOK_SLASH_ASSIGN||k==TOK_PERCENT_ASSIGN?AST_ASSIGN:AST_BINARY,k,l,binary(p,q+(k==TOK_ASSIGN?0:1)));}return l;}
static ast_node_t*expr(gc_parser_t*p){return binary(p,1);}
static ast_node_t*declaration(gc_parser_t*p,u8 global){gc_type_t*t;char*n;u32 z;ast_node_t*v;t=parse_type(p);if(p->current.kind==TOK_SEMICOLON){v=ast_new(AST_STRUCT_DECL);v->type=t;advance_p(p);return v;}if(p->current.kind!=TOK_IDENT){p->error_count++;return 0;}n=dup_n(p->current.start,p->current.length);z=p->current.length;advance_p(p);if(take(p,TOK_LPAREN)){ast_node_t*f=ast_new(AST_FUNC_DECL);f->as.func.name=n;f->as.func.return_type=type_node(t);f->type=type_function(t,0,0);symtab_insert(p->symtab,n,z,SYM_FUNC);while(p->current.kind!=TOK_RPAREN&&p->current.kind!=TOK_EOF){gc_type_t*pt=parse_type(p);if(p->current.kind!=TOK_IDENT){p->error_count++;break;}v=ast_new(AST_VAR_DECL);v->as.var.name=dup_n(p->current.start,p->current.length);v->as.var.name_len=p->current.length;v->as.var.var_type=type_node(pt);v->as.var.sym=symtab_insert(p->symtab,v->as.var.name,v->as.var.name_len,SYM_VAR);list_add(&f->as.func.params,v);advance_p(p);if(!take(p,TOK_COMMA))break;}expect(p,TOK_RPAREN);if(!take(p,TOK_SEMICOLON))f->as.func.body=stmt(p);return f;}v=ast_new(AST_VAR_DECL);v->as.var.name=n;v->as.var.name_len=z;v->as.var.var_type=type_node(t);v->as.var.is_global=global;if(take(p,TOK_LBRACKET)){u32 count=p->current.value;expect(p,TOK_NUMBER);expect(p,TOK_RBRACKET);v->as.var.var_type->type=type_array(t,count);}if(take(p,TOK_ASSIGN)){if(take(p,TOK_LBRACE)){while(p->current.kind!=TOK_RBRACE&&p->current.kind!=TOK_EOF){if(p->current.kind==TOK_NUMBER)advance_p(p);else p->error_count++;if(!take(p,TOK_COMMA))break;}expect(p,TOK_RBRACE);}else v->as.var.init=expr(p);}expect(p,TOK_SEMICOLON);v->as.var.sym=symtab_insert(p->symtab,n,z,SYM_VAR);v->as.var.sym->type=v->as.var.var_type->type;return v;}
static ast_node_t*stmt(gc_parser_t*p){ast_node_t*n;if(take(p,TOK_LBRACE)){n=ast_new(AST_COMPOUND);symtab_push_scope(p->symtab);while(p->current.kind!=TOK_RBRACE&&p->current.kind!=TOK_EOF){if(p->current.kind==TOK_INT||p->current.kind==TOK_CHAR_KW||p->current.kind==TOK_STRUCT||p->current.kind==TOK_IDENT)list_add(&n->as.list,declaration(p,0));else list_add(&n->as.list,stmt(p));}expect(p,TOK_RBRACE);symtab_pop_scope(p->symtab);return n;}if(take(p,TOK_RETURN)){n=ast_new(AST_RETURN);if(p->current.kind!=TOK_SEMICOLON)n->as.ret.expr=expr(p);expect(p,TOK_SEMICOLON);return n;}if(take(p,TOK_IF)){n=ast_new(AST_IF);expect(p,TOK_LPAREN);n->as.branch.cond=expr(p);expect(p,TOK_RPAREN);n->as.branch.then_body=stmt(p);if(take(p,TOK_ELSE))n->as.branch.else_body=stmt(p);return n;}if(take(p,TOK_WHILE)){n=ast_new(AST_WHILE);expect(p,TOK_LPAREN);n->as.branch.cond=expr(p);expect(p,TOK_RPAREN);n->as.branch.then_body=stmt(p);return n;}if(take(p,TOK_FOR)){n=ast_new(AST_FOR);expect(p,TOK_LPAREN);if(p->current.kind!=TOK_SEMICOLON)n->as.for_loop.init=expr(p);expect(p,TOK_SEMICOLON);if(p->current.kind!=TOK_SEMICOLON)n->as.for_loop.cond=expr(p);expect(p,TOK_SEMICOLON);if(p->current.kind!=TOK_RPAREN)n->as.for_loop.step=expr(p);expect(p,TOK_RPAREN);n->as.for_loop.body=stmt(p);return n;}if(take(p,TOK_DO)){n=ast_new(AST_DO_WHILE);n->as.do_loop.body=stmt(p);expect(p,TOK_WHILE);expect(p,TOK_LPAREN);n->as.do_loop.cond=expr(p);expect(p,TOK_RPAREN);expect(p,TOK_SEMICOLON);return n;}if(take(p,TOK_BREAK)){n=ast_new(AST_BREAK);expect(p,TOK_SEMICOLON);return n;}if(take(p,TOK_CONTINUE)){n=ast_new(AST_CONTINUE);expect(p,TOK_SEMICOLON);return n;}n=ast_new(AST_EXPR_STMT);n->as.expr_stmt.expr=expr(p);expect(p,TOK_SEMICOLON);return n;}
int gc_parser_init(gc_parser_t*p,gc_lexer_t*l,symtab_t*s){memset(p,0,sizeof(*p));p->lexer=l;p->symtab=s;gc_lex_next(l,&p->current);gc_lex_next(l,&p->peek);return 0;}
ast_node_t*gc_parse_program(gc_parser_t*p){ast_node_t*n=ast_new(AST_PROGRAM);while(p->current.kind!=TOK_EOF){if(p->current.kind==TOK_TYPEDEF){advance_p(p);gc_type_t*t=parse_type(p);if(p->current.kind==TOK_IDENT){ast_node_t*d=ast_new(AST_TYPEDEF);d->as.typedef_decl.name=dup_n(p->current.start,p->current.length);d->as.typedef_decl.name_len=p->current.length;d->as.typedef_decl.type=t;symbol_t*x=symtab_insert(p->symtab,d->as.typedef_decl.name,d->as.typedef_decl.name_len,SYM_TYPE);x->type=t;list_add(&n->as.list,d);advance_p(p);expect(p,TOK_SEMICOLON);}else p->error_count++;}else if(p->current.kind==TOK_INT||p->current.kind==TOK_CHAR_KW||p->current.kind==TOK_VOID||p->current.kind==TOK_STRUCT||p->current.kind==TOK_UNION||p->current.kind==TOK_IDENT)list_add(&n->as.list,declaration(p,1));else{p->error_count++;advance_p(p);}}return n;}
int gc_typecheck(ast_node_t*n,symtab_t*s){(void)n;(void)s;return 0;}
